Exercise 1: K-Nearest Neighbor

Let us implement the algorithm with the help of the 'Mobile.csv' dataset.

It contains data about customers “Age”, “EstimatedSalary”, “Purchased” .

Download the dataset from the shared folder.


Predict if the customer will purchase a mobile or not.

Load data : mobile.csv

In [16]:
import numpy as numpy
import pandas as pd
# import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv('dataset/mobile.csv')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [19]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [20]:
df.tail()

     Age  EstimatedSalary  Purchased
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [21]:
df["Purchased"].unique()

array([0, 1])

In [22]:
df.isna().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [23]:
purchased_data = df[["Age", "EstimatedSalary", "Purchased"]][df["Purchased"]==1]
purchased_data

     Age  EstimatedSalary  Purchased
7     32           150000          1
16    47            25000          1
17    45            26000          1
18    46            28000          1
19    48            29000          1
..   ...              ...        ...
393   60            42000          1
395   46            41000          1
396   51            23000          1
397   50            20000          1
399   49            36000          1

[143 rows x 3 columns]

In [24]:
not_purchased_data = df[["Age", "EstimatedSalary", "Purchased"]][df["Purchased"]==0]
not_purchased_data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
377   42            53000          0
380   42            64000          0
387   39            71000          0
394   39            59000          0
398   36            33000          0

[257 rows x 3 columns]

In [25]:
plt.scatter(purchased_data["Age"], purchased_data["EstimatedSalary"], c='green')
plt.scatter(not_purchased_data["Age"], not_purchased_data["EstimatedSalary"], c='red')

NameError: name 'plt' is not defined

In [ ]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
df["Age"].max()

60

In [ ]:
df["Age"].min()

18

In [ ]:
df["EstimatedSalary"].max()

150000

In [ ]:
df["EstimatedSalary"].min()

15000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
features_to_scale = ["Age", "EstimatedSalary"]
scaled_values = scaler.fit_transform(df[features_to_scale])

In [ ]:
df["norm_age"] = scaled_values[:,0]
df["norm_salary"] = scaled_values[:,1]

In [ ]:
df

     Age  EstimatedSalary  Purchased  norm_age  norm_salary
0     19            19000          0  0.023810     0.029630
1     35            20000          0  0.404762     0.037037
2     26            43000          0  0.190476     0.207407
3     27            57000          0  0.214286     0.311111
4     19            76000          0  0.023810     0.451852
..   ...              ...        ...       ...          ...
395   46            41000          1  0.666667     0.192593
396   51            23000          1  0.785714     0.059259
397   50            20000          1  0.761905     0.037037
398   36            33000          0  0.428571     0.133333
399   49            36000          1  0.738095     0.155556

[400 rows x 5 columns]

In [ ]:
df["norm_age"].min()

0.0

In [ ]:
df["norm_age"].max()

0.9999999999999998

In [ ]:
X = df[["norm_age", "norm_salary"]]
y = df[["Purchased"]]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (320, 2)
Shape of y_train: (320, 1)
Shape of X_test: (80, 2)
Shape of y_test: (80, 1)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5, metric="euclidean")
model.fit(X_train, y_train)

c:\Users\raghu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(metric='euclidean')

In [ ]:
model.score(X_test,y_test) * 100

95.0

In [ ]:
import pandas as pd
import numpy as np

In [72]:
x = pd.read_csv('iris.csv')

In [73]:
v_nv_fn = lambda x: 0 if x == "versicolor" else 1
iris_data['v_nv'] = iris_data['species'].apply(v_nv_fn)
iris_data

NameError: name 'iris_data' is not defined

In [ ]:
import seaborn as sns
sns.pairplot(iris_data),
            x_vars = "petal.length",
            y_vars = "petal.width",
            hue= "v_nv",height=5