Tutorial 4: Implement Decision tree and Naive bayes

|1|2|3|
|-|-|-|
|6|0|9|
|7|_|8|

# heADING


## STEP1
>POINT
### TOPIC

# **BOLD**
# *ITALIC*
# ***ib***

>BULLET

Exercise 1: Decision Tree

Load dataset users.csv
Assign predictors and targets.
Apply encoding using get_dummies().
Split the dataset into train and test data.
Building the model using a decision tree.
Draw decision tree.
Evaluate model performance on train and test sets

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('../ML Practicals/users.csv')
df

     User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   12            19000          0
1   15810944    Male   11            20000          0
2   15668575  Female    1            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   10            76000          0
..       ...     ...  ...              ...        ...
94  15786993  Female   45            83000          0
95  15709441  Female   35            44000          0
96  15710257  Female    4            25000          0
97  15582492    Male    5           123000          1
98  15575694    Male   35            73000          0

[99 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          99 non-null     int64
 1   Gender           99 non-null     object
 2   Age              99 non-null     int64
 3   EstimatedSalary  99 non-null     int64
 4   Purchased        99 non-null     int64
dtypes: int64(4), object(1)
memory usage: 4.0+ KB

In [4]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   12            19000          0
1  15810944    Male   11            20000          0
2  15668575  Female    1            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   10            76000          0

In [5]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
df['Purchased'].unique()

array([0, 1])

In [7]:
X = df.columns.drop('Purchased')
y = df['Purchased']

In [8]:
df_encoded = pd.get_dummies(df[X]).astype(int)

In [9]:
df_encoded

     User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
0   15624510   12            19000              0            1
1   15810944   11            20000              0            1
2   15668575    1            43000              1            0
3   15603246   27            57000              1            0
4   15804002   10            76000              0            1
..       ...  ...              ...            ...          ...
94  15786993   45            83000              1            0
95  15709441   35            44000              1            0
96  15710257    4            25000              1            0
97  15582492    5           123000              0            1
98  15575694   35            73000              0            1

[99 rows x 5 columns]

In [10]:
X = df.iloc[:, :-1]   # Features
y = df.iloc[:, -1]

In [11]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes of the resulting datasets
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (79, 4)
Shape of X_test: (20, 4)
Shape of y_train: (79,)
Shape of y_test: (20,)

In [1]:

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='gini', random_state=1)
model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(user_encoded, y, test_size=0.15, random_state=0)
print