In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
data = pd.read_csv("dataset/users.csv")

In [3]:
data

     User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   12            19000          0
1   15810944    Male   11            20000          0
2   15668575  Female    1            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   10            76000          0
..       ...     ...  ...              ...        ...
94  15786993  Female   45            83000          0
95  15709441  Female   35            44000          0
96  15710257  Female    4            25000          0
97  15582492    Male    5           123000          1
98  15575694    Male   35            73000          0

[99 rows x 5 columns]

In [4]:
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   12            19000          0
1  15810944    Male   11            20000          0
2  15668575  Female    1            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   10            76000          0

In [5]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
data['Age'].unique()

array([12, 11,  1, 27, 10,  7,  5,  8,  9,  4,  2,  6,  3, 51, 30, 28, 45,
       23, 32, 54, 20, 64, 46, 18, 26, 35, 24], dtype=int64)

In [6]:
data['Purchased'].unique()

array([0, 1], dtype=int64)

In [9]:
X = data.columns.drop('Purchased')
y = data['Purchased']

In [10]:
X
y

0     0
1     0
2     0
3     0
4     0
     ..
94    0
95    0
96    0
97    1
98    0
Name: Purchased, Length: 99, dtype: int64

In [12]:
data_encoded = pd.get_dummies(data[X]).astype(int)

In [13]:
data_encoded

     User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
0   15624510   12            19000              0            1
1   15810944   11            20000              0            1
2   15668575    1            43000              1            0
3   15603246   27            57000              1            0
4   15804002   10            76000              0            1
..       ...  ...              ...            ...          ...
94  15786993   45            83000              1            0
95  15709441   35            44000              1            0
96  15710257    4            25000              1            0
97  15582492    5           123000              0            1
98  15575694   35            73000              0            1

[99 rows x 5 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_text,y_train,y_text

In [15]:
from sklearn.tree import  DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'gini',random_state=1)
model.fit(X_train,y_train)

NameError: name 'X_train' is not defined